# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WildFly JAR Maven Plugin - CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'examples/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'examples/**'

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}-jdk${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]
        java: ['11', '17', '21']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and Test on ${{ matrix.java }}
        # Some tests start the server with large default configurations, on Windows CI it has been observed some failure caused by reaching mem limits.
        run: mvn clean install '-Dtest.jvm.args=-Xms1g -Xmx1g -Dorg.wildfly.logging.skipLogManagerCheck=true' '-Dorg.wildfly.bootable.jar.ci.execution=true'
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: | 
           !**/bootable-jar-build-artifacts/**
           **/surefire-reports/
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: |
           !**/bootable-jar-build-artifacts/**
           **/server.log
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: devwatch-logs-${{ matrix.os }}-${{ matrix.java }}
          path: |
           !**/bootable-jar-build-artifacts/**
           **/dev-watch-test-output.txt
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: project-src-${{ matrix.os }}-${{ matrix.java }}
          path: |
           !**/bootable-jar-build-artifacts/**
           **/tests/target/devwatch*/src/**
           **/tests/target/devwatch*/target/deployments/**
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: logs-${{ matrix.os }}-${{ matrix.java }}
          path: | 
           !**/bootable-jar-build-artifacts/**
           **/tests/**/logs/**
